trigger_detection:
  name: Trigger Detection
  description: Forces a manual detection run on the selected Obico ML API Wrapper instance.
  target:
    entity:
      integration: obico_ml
    device:
      integration: obico_ml